//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_SMPEntities : DbContext
    {
        public DB_SMPEntities()
            : base("name=DB_SMPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_cat> tb_cat { get; set; }
        public virtual DbSet<TB_Cus> TB_Cus { get; set; }
        public virtual DbSet<TB_Pur> TB_Pur { get; set; }
        public virtual DbSet<TB_SUPP> TB_SUPP { get; set; }
        public virtual DbSet<TB_Sell> TB_Sell { get; set; }
        public virtual DbSet<TB_Users> TB_Users { get; set; }
    }
}
