//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Pur
    {
        public int Pur_Id { get; set; }
        public Nullable<int> Supp_Id { get; set; }
        public string Pur_Name { get; set; }
        public string Pur_Type { get; set; }
        public string Pur_Cat { get; set; }
        public string Pur_Supp { get; set; }
        public string Pur_Det { get; set; }
        public Nullable<double> Pur_Buy { get; set; }
        public Nullable<double> Pur_Sell { get; set; }
        public Nullable<double> Pur_Qt { get; set; }
        public Nullable<double> Pur_TSell { get; set; }
        public Nullable<double> Pur_TBuy { get; set; }
        public Nullable<double> Pur_TRev { get; set; }
        public Nullable<int> Cat_Id { get; set; }
    
        public virtual tb_cat tb_cat { get; set; }
        public virtual TB_SUPP TB_SUPP { get; set; }
    }
}
