//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Sell
    {
        public int Sell_Id { get; set; }
        public string Sell_Name { get; set; }
        public string Sell_Cus { get; set; }
        public Nullable<double> Sell_Price { get; set; }
        public Nullable<double> Sell_Qte { get; set; }
        public Nullable<double> Sell_Tprice { get; set; }
        public Nullable<System.DateTime> Sell_Date { get; set; }
    }
}
