//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMP
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Users
    {
        public int User_Id { get; set; }
        public string User_Name { get; set; }
        public string User_Pass { get; set; }
        public string User_Roll { get; set; }
        public string User_State { get; set; }
    }
}
