using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using SMP.EPL;
namespace SMP.PL
{
    public partial class FrmPur: Form
    {
        DB_SMPEntities db = new DB_SMPEntities();
        // elements for delete function
        TB_SUPP tb_Supp = new TB_SUPP();
        TB_Pur tb_Pur = new TB_Pur();
        BL.Methods methods = new BL.Methods();
        int id;
        public FrmPur()
        {
            InitializeComponent();


            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            SMP.DB_SMPEntities dbContext = new SMP.DB_SMPEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_Pur.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControlPur.DataSource = dbContext.TB_Pur.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            PL.FrmPurAdd frmAddPur = new PL.FrmPurAdd();
            frmAddPur.id = 0;
            frmAddPur.btnAddPur.Text = "اضافة";
            frmAddPur.Show();
        }

        private void btnUpdate_Click(object sender, EventArgs e)
        {
             db  = new DB_SMPEntities();
            gridControlPur.DataSource = db.TB_Pur.ToList();
        }

        // delete purchase
        private void btnDel_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            Dialog dialog = new Dialog();
            id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("Pur_Id"));
            if(id>0)
            {
                try
                {
                    var rs = MessageBox.Show("عملية حذف", "هل أنت متأكد من هذه العملية", MessageBoxButtons.YesNo);

                    if (rs == DialogResult.Yes)
                    {
                        tb_Pur = db.TB_Pur.Where(x => x.Pur_Id == id).FirstOrDefault();
                        db.Entry(tb_Pur).State = EntityState.Deleted;
                        db.SaveChanges();
                        toast.txtCaption.Text = "تم حذف عملية شراء";
                        toast.Show();
                        updateData();
                    }
                }
                catch
                {
                    dialog.txtCaption.Text = "لا يوجد عملية شراء لحذفها ";
                    dialog.Width = this.Width;
                    dialog.Show();


                }
            }
            else
            {
                dialog.txtCaption.Text = "لا يوجد عملية شراء لحذفه ";
                dialog.Width = this.Width;
                dialog.Show();
            }
            


        }
        //function update data in gridview
        public void updateData()
        {
            Dialog dialog = new Dialog();

            db = new DB_SMPEntities();
            gridControlPur.DataSource = db.TB_Pur.ToList();
            
            // add notification to the user if quantite equall 0
            if(tb_Pur.Pur_Qt==0)
            {
                dialog.txtCaption.Text = "الكمية نفدت ";
                dialog.Width = this.Width;
                dialog.Show();            }
        }

        private void btnSearch_Click(object sender, EventArgs e)
        {
            var _search = editSearch.Text;
            gridControlPur.DataSource = db.TB_Pur.Where(x => x.Pur_Name.Contains(_search)||
                                                          x.Pur_Type.Contains(_search)||
                                                          x.Pur_Cat.Contains(_search) || 
                                                          x.Pur_Supp.Contains(_search) ||
                                                          x.Pur_Det.Contains(_search)  ).ToList();
        }
        // edit supplier
        private void btnEdit_Click(object sender, EventArgs e)
        {
            PL.FrmPurAdd frmAddPur = new PL.FrmPurAdd();
            Toast toast = new Toast();
            Dialog dialog = new Dialog();
            try
            {
                id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("Pur_Id"));
                tb_Pur = db.TB_Pur.Where(x => x.Pur_Id == id).FirstOrDefault();
                if (tb_Pur != null)
                {
                    frmAddPur.editNamePur.Text = tb_Pur.Pur_Name;
                    frmAddPur.editTypePur.Text = tb_Pur.Pur_Type;
                    frmAddPur.editCat.Text = tb_Pur.Pur_Cat;
                    frmAddPur.editSup.Text = tb_Pur.Pur_Supp;
                    frmAddPur.editPurDet.Text = tb_Pur.Pur_Det;

                    frmAddPur.editBuy.Text = tb_Pur.Pur_Buy.ToString();
                    frmAddPur.editSell.Text = tb_Pur.Pur_Sell.ToString();
                    frmAddPur.editQte.Text = tb_Pur.Pur_Qt.ToString();

                    frmAddPur.editTBuy.Text = tb_Pur.Pur_TBuy.ToString();
                    frmAddPur.editTSell.Text = tb_Pur.Pur_TSell.ToString();
                    frmAddPur.editTRev.Text = tb_Pur.Pur_TRev.ToString();
                    frmAddPur.id = id;
                    frmAddPur.btnAddPur.Text = " تعديل ";
                    frmAddPur.Show();
                    updateData();
                }
                else
                {
                    toast.txtCaption.Text = "لا يوجد عملية شراء لتعديلها ";
                    toast.Show();
                }
            }
            catch

            {
                toast.txtCaption.Text = "لا يوجد عملية شراء لتعديله ";
                toast.Show();
            }

        }

       
    }
}
