using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using SMP.EPL;
namespace SMP.PL
{
    public partial class FrmSup: Form
    {
        DB_SMPEntities db = new DB_SMPEntities();
        // elements for delete function
        TB_SUPP tb_Supp = new TB_SUPP();
        BL.Methods methods = new BL.Methods();
        int id;
        public FrmSup()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            SMP.DB_SMPEntities dbContext = new SMP.DB_SMPEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_SUPP.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    gridControlSupp.DataSource = dbContext.TB_SUPP.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            PL.FrmSuppAdd frmAddSupp = new PL.FrmSuppAdd();
            frmAddSupp.id = 0;
            frmAddSupp.btnAddSupp.Text = "اضافة";
            frmAddSupp.Show();
            //updateData();
        }

        private void btnUpdate_Click(object sender, EventArgs e)
        {
             db  = new DB_SMPEntities();
            gridControlSupp.DataSource = db.TB_SUPP.ToList();
        }

        // delete supplier
        private void btnDel_Click(object sender, EventArgs e)
        {
            Toast toast = new Toast();
            Dialog dialog = new Dialog();
            id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("Supp_Id"));
            if(id>0)
            {
                try
                {
                    var rs = MessageBox.Show("عملية حذف", "هل أنت متأكد من هذه العملية", MessageBoxButtons.YesNo);

                    if (rs == DialogResult.Yes)
                    {
                        tb_Supp = db.TB_SUPP.Where(x => x.Supp_Id == id).FirstOrDefault();
                        db.Entry(tb_Supp).State = EntityState.Deleted;
                        db.SaveChanges();
                        toast.txtCaption.Text = "تم حذف مورد";
                        toast.Show();
                        updateData();
                    }
                }
                catch
                {
                    dialog.txtCaption.Text = "لا يوجد مورد لحذفه ";
                    dialog.Width = this.Width;
                    dialog.Show();


                }
            }
            else
            {
                dialog.txtCaption.Text = "لا يوجد مورد لحذفه ";
                dialog.Width = this.Width;
                dialog.Show();
            }
            


        }
        //function update data in gridview
        public void updateData()
        {
            db = new DB_SMPEntities();
            gridControlSupp.DataSource = db.TB_SUPP.ToList();
        }

        private void btnSearch_Click(object sender, EventArgs e)
        {
            var _search = editSearch.Text;
            gridControlSupp.DataSource = db.TB_SUPP.Where(x => x.Supp_Name.Contains(_search)||
                                                          x.Supp_Phone.Contains(_search)||
                                                          x.Supp_Email.Contains(_search)).ToList();
        }
        // edit supplier
        private void btnEdit_Click(object sender, EventArgs e)
        {
            PL.FrmSuppAdd frmAddSup = new PL.FrmSuppAdd();
            Toast toast = new Toast();
            Dialog dialog = new Dialog();
            try
            {
                id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("Supp_Id"));
                tb_Supp = db.TB_SUPP.Where(x => x.Supp_Id == id).FirstOrDefault();
                if (tb_Supp != null)
                {
                    frmAddSup.editNameSup.Text = tb_Supp.Supp_Name.ToString();
                    frmAddSup.editPhoneSupp.Text = tb_Supp.Supp_Phone.ToString();
                    frmAddSup.edtEmailSupp.Text = tb_Supp.Supp_Email.ToString();


                    methods.by = tb_Supp.Supp_Image;
                    frmAddSup.picCoverSupp.Image = Image.FromStream(methods.convertImage());
                    frmAddSup.id = id;
                    frmAddSup.btnAddSupp.Text = "تعديل";
                    frmAddSup.Show();
                    updateData();

                }
                else
                {
                    toast.txtCaption.Text = "لا يوجد مورد لتعديله ";
                    toast.Show();
                }
                
            }
            catch
            {
                toast.txtCaption.Text = "لا يوجد مورد لتعديله ";
                toast.Show();

            }




        }

       
    }
}
